Move XmlDocWrapper to Common.Lib (#402)
This is so it can be used by Nagler as well, as part of the effort
 to get Nagler running on Windows and Linux.

There are multiple steps to this.

1) Remove CEncoding and replace it with systemstring
    -XmlDocWrapper depended on CEncoding, but CEncoding depended
     on ATL libraries that depended on the PAL. CEncoding has been
     been replaced by systemstring which uses only functions that
     are native to the OS.
2) Remove XmlDocWrapper's dependency on BSTR and AutoVectorPointer
    - tstring is a better cross-plat solution. XmlDocWrapper now uses
      systemstring and tstring instead of depending on Windows types.
3) Move XmlDocWrapper into Common.Lib
4) While I was here, I simplified ConfigurationLoader to
    use XmlDocWrapper so that all of our xml reading is consistent.

To support these changes, additional cross-platform unit tests have been
added. This involves:

1) Adding a dependency on googletest for running cross-plat c++ tests.
2) Updating the minimum version of cmake to 3.14 (needed for googletest)
4) Adding unit tests for systemstring, and XmlDocWrapper
5) Moving the ConfigurationLoaderTests into a new cross-plat test.

While doing this work, I found a couple of bugs:

1) XmlDocWrapper behaved differently on Windows and Linux. This has been
    fixed.
2) Previous move of ImplQueryInterface makes an undefined reference to
    IID_IUnknown. The necessary IID has been added for Linux systems.

closes #359